### ISSUE TITLE
Turtle serialization uses wrong literal representation

### ISSUE THREAD

**Issue by VladimirAlexiev** [periodo/periodo-server#59] opened 2016-12-05 09:23 UTC
Eg https://test.perio.do/#/p/Canonical/periodCollections/p07h9k6/?show_period=p07h9k6npwn
```turtle
<http://n2t.net/ark:/99152/p07h9k6> a skos:ConceptScheme;
      dcterms:issued <"2014"^^xsd:gYear>.
<http://n2t.net/ark:/99152/p07h9k62chw> a skos:Concep;
    time:intervalFinishedBy [
      skos:prefLabel "-200000";
      time:hasDateTimeDescription [
        time:year <"-200000"^^xsd:gYear>
      ]
```
Should be `"2014"^^xsd:gYear` and `"-200000"^^xsd:gYear` respectively (without the angle brackets).

**Comment by rybesh** [comment] 2016-12-05 15:15
Duplicate of https://github.com/periodo/periodo-client/issues/111

**Closed by rybesh** 2016-12-05 15:15 UTC
