### ISSUE TITLE
Publish RSS feeds for changes

### ISSUE THREAD

**Issue by ptgolden** [periodo/periodo-server#55] opened 2016-04-14 02:06 UTC

**Comment by rybesh** [comment] 2018-01-09 02:47
@ptgolden What do you think about changing our history JSON-LD to be valid [JSON Feed](https://jsonfeed.org/version/1)?

**Comment by rybesh** [comment] 2018-01-10 16:26
Actually it might make more sense to have the list of patch requests be a feed, rather than the (extremely voluminous) full change history. This would make it easy to monitor for new patch submissions.

**Comment by rybesh** [comment] 2020-05-12 23:10
duplicate of #154

**Closed by rybesh** 2020-05-12 23:10 UTC
Labels: enhancement
